/:
  controller: "Home"
  action: "index"

/s-inscrire:
  controller: "User"
  action: "register"

/se-connecter:
  controller: "User"
  action: "login"

/se-deconnecter:
  controller: "User"
  action: "logout"

/utilisateurs/{id}/modifier:
  controller: "User"
  action: "edit"

/utilisateurs/{id}/update:
  controller: "User"
  action: "update"

/oublie-motdepasse:
  controller: "User"
  action: "forgotPassword"

/reset-motdepasse:
  controller: "User"
  action: "resetPassword"
