/:
  controller: "Home"
  action: "index"

/register:
  controller: "User"
  action: "register"

/se-connecter:
  controller: "User"
  action: "login"

/se-deconnecter:
  controller: "User"
  action: "logout"

/backoffice:
  controller: "Backoffice"
  action: "dashboard"

/page:
  controller: "page"
  action: "show"

/register/confirm:
  controller: "User"
  action: "register"