/:
  controller: "Home"
  action: "index"

/s-inscrire:
  controller: "User"
  action: "register"

/se-connecter:
  controller: "User"
  action: "login"

/se-deconnecter:
  controller: "User"
  action: "logout"

/backoffice:
  controller: "Backoffice"
  action: "dashboard"
